development:
  adapter: postgresql
  encoding: utf8
  database: login_counter_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: login_counter_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: login_counter_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST

